In [42]:
#imports 
import numpy as np

## Práctico N°2
Dada la siguiene serie de python, crear un array en NumPy:
`87, 53, 27, 45, 30, 84, 85, 17, 14`
* A-Obtener los primero 4 valores de la serie.
* B-Convertir a una matrix de 3x3.
* C-Obtener los máximos de cada fila.
* D-Obtener los mínimos de cada columna.


In [37]:
number_serie = np.array([87, 53, 27, 45, 30, 84, 85, 17, 14])
# A. obtener los primeros 4 valores
print(number_serie[:4])
# B. convertir a matriz 3x3
number_serie = number_serie.reshape(3, 3)
print(number_serie)
# C Obtener los máximos de cada fila.
print(number_serie.max(axis=1))
# D Obtener los mínimos de cada columna.
print(number_serie.min(axis=0))

[87 53 27 45]
[[87 53 27]
 [45 30 84]
 [85 17 14]]
[87 84 85]
[45 17 14]


* Crear un array de 4 dimensiones 3 filas, 4 columnas, agrupados en 2 grupos de 3 matrices con numeros enteros aleatorios entre 3 y 30.
* Calcular la amplitud por columnas de la segunda matriz del primer grupo.
* Calcular la amplitud por filas de la ultima matriz del ultimo grupo(sin tener en cuenta el total de grupos ni de matrices por grupo)

In [38]:
# Array 3*4*2*1 aleatorio
array = np.random.randint(1, 10, (1, 2, 4, 3, 3))
print(array)

[[[[[9 5 3]
    [8 5 4]
    [3 8 9]]

   [[8 2 7]
    [2 7 7]
    [1 1 2]]

   [[5 3 3]
    [3 6 1]
    [4 5 5]]

   [[6 1 9]
    [7 9 8]
    [4 6 9]]]


  [[[3 8 8]
    [9 8 4]
    [4 1 8]]

   [[7 8 4]
    [6 1 1]
    [9 1 2]]

   [[9 9 3]
    [7 2 1]
    [3 3 8]]

   [[2 2 2]
    [3 5 6]
    [3 4 6]]]]]


Dado el siguiente array averigura:
* Cantas dimensiones e instancias tiene de cada una.
* Convertir el array en 4 grupos de 3 matrices de 9 columnas (calcular las filas)

In [39]:
arr = np.array([[[[25, 26,  5, 26,  5, 17, 16, 17,  4],[16, 19, 15, 12, 18, 20, 21, 20, 28],[18, 29, 14, 24, 18, 27, 25,  6, 28],[26,  3,  7,  5,  4,  6, 14, 25, 23],[24,  7, 24, 20, 24, 15, 24, 17, 23],[ 5, 25, 14,  7, 16, 19, 29, 22, 13]],[[28, 26,  5, 27, 16, 23, 14,  4, 17],[18, 13,  6,  7, 11,  6,  7,  8, 24],[18, 21, 16,  3,  9,  3, 20, 14, 25],[17,  3,  7, 28, 22, 28, 12,  8, 29],[24, 12, 11, 22, 15, 21,  7, 12, 28],[ 6, 24, 10, 26, 10, 29,  7, 23, 20]],[[ 7, 15,  7, 24, 13, 28, 14, 26, 16],[17,  5,  7, 29, 20, 17, 21, 16, 21],[23, 22, 14, 25, 27,  3,  8,  4, 20],[12, 17, 16, 22, 15,  6, 17,  8, 22],[23,  8, 22, 29,  5, 23, 21,  8,  9],[13,  6, 11, 14,  5, 20, 20, 16, 26]]],[[[18,  7,  5, 18, 23,  9, 21, 16, 26],[11, 10,  9,  4,  6,  4,  6, 13, 14],[25, 13, 13, 18, 24, 18,  7, 20, 28],[27, 25, 17, 10, 25,  3,  3,  8,  7],[25, 16, 18, 11,  6, 18, 21,  6, 13],[29,  9,  4, 24, 10, 26, 13, 18, 14]],[[ 8,  9, 13, 29, 26,  4, 27, 26, 14],[16,  8, 15,  4, 18, 16, 23, 27, 21],[29, 13,  6,  9,  8,  6, 25,  3, 29],[17, 12, 19,  4, 22,  3, 12, 19, 15],[29, 29,  7, 10,  3, 15,  4, 28,  4],[ 6, 11,  3, 22, 14, 20,  8,  9, 13]],[[26,  8,  6,  5,  9, 24, 24, 15, 18],[28, 21, 23, 28, 25,  8, 19, 19, 21],[24,  7, 10,  9, 12, 21, 14, 27, 10],[25,  6, 23, 26, 23, 14, 17,  9, 12],[24, 10, 28, 29, 15, 25,  5, 14,  3],[25, 18, 28, 19, 23, 29, 16, 20,  8]]]])

In [40]:
print(arr.ndim)
for i in range(arr.ndim):
    print(f"Las ocurrencias de la dimension {i} son:{arr.shape[i]}")
print(f"el total de valores es:{arr.size}")
print(arr.reshape(3,9,12))

4
Las ocurrencias de la dimension 0 son:2
Las ocurrencias de la dimension 1 son:3
Las ocurrencias de la dimension 2 son:6
Las ocurrencias de la dimension 3 son:9
el total de valores es:324
[[[25 26  5 26  5 17 16 17  4 16 19 15]
  [12 18 20 21 20 28 18 29 14 24 18 27]
  [25  6 28 26  3  7  5  4  6 14 25 23]
  [24  7 24 20 24 15 24 17 23  5 25 14]
  [ 7 16 19 29 22 13 28 26  5 27 16 23]
  [14  4 17 18 13  6  7 11  6  7  8 24]
  [18 21 16  3  9  3 20 14 25 17  3  7]
  [28 22 28 12  8 29 24 12 11 22 15 21]
  [ 7 12 28  6 24 10 26 10 29  7 23 20]]

 [[ 7 15  7 24 13 28 14 26 16 17  5  7]
  [29 20 17 21 16 21 23 22 14 25 27  3]
  [ 8  4 20 12 17 16 22 15  6 17  8 22]
  [23  8 22 29  5 23 21  8  9 13  6 11]
  [14  5 20 20 16 26 18  7  5 18 23  9]
  [21 16 26 11 10  9  4  6  4  6 13 14]
  [25 13 13 18 24 18  7 20 28 27 25 17]
  [10 25  3  3  8  7 25 16 18 11  6 18]
  [21  6 13 29  9  4 24 10 26 13 18 14]]

 [[ 8  9 13 29 26  4 27 26 14 16  8 15]
  [ 4 18 16 23 27 21 29 13  6  9  8  6]
  [25  

* Dado el siguiente array con la información de alumnos, agregar las notas de las materias que faltan que se encuentran en el arr2
* Mostrar en un array el promedio de cada alumno (solo 2 decimales)
* Mostrar el un arrayo con el promedio por materias (solo 2 decimales)
* Generar una lista con los nombre de los alumnos que aprobaron con mas de 7 matemáticas
* Generar una lista con los alumnos que obtubieron menos 7 en base de datos.

In [ ]:


# Datos originales
arr1 = np.array([
    ["Nombre","Matemáticas","Estadísticas","Algebra","Ingles"],
    ["María",7,5,7,8],
    ["Sebastián",8,6,6,9],
    ["Javier",8,8,4,7],
    ["Cristian",4,5,3,9],
    ["Julia",8,8,9,8],
    ["Facundo",9,3,6,10],
    ["Ariel",9,9,8,10]
], dtype=object)

arr2 = ["Algoritmos",4,8,7,9,9,8,6,"Base de Datos",7,6,5,6,5,8,9]

# Extraer notas
algoritmos = arr2[1:8]
base_datos = arr2[9:]

# Agregar columnas
arr1 = np.column_stack((arr1, ["Algoritmos"] + algoritmos, ["Base de Datos"] + base_datos))

print("Array con todas las materias:")
print(arr1)

# Convertir solo las notas a float para cálculos (ignorando la cabecera)
notas = arr1[1:, 1:].astype(float)

# Promedio de cada alumno (solo 2 decimales)
promedios_alumnos = np.round(notas.mean(axis=1), 2)
print("\nPromedio de cada alumno:")
print(promedios_alumnos)

# Promedio por materia (solo 2 decimales)
promedios_materias = np.round(notas.mean(axis=0), 2)
print("\nPromedio por materia:")
print(promedios_materias)

# Alumnos que aprobaron matemáticas con más de 7
print("\nAlumnos con más de 7 en Matemáticas:")
for i, nota in enumerate(notas[:, 0]):
    if nota > 7:
        print(arr1[i+1, 0])

# Alumnos con menos de 7 en Base de Datos
print("\nAlumnos con menos de 7 en Base de Datos:")
for i, nota in enumerate(notas[:, -1]):
    if nota < 7:
        print(arr1[i+1, 0])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 8 and the array at index 1 has size 9